services:
  backend:
    build: ./server
    env_file:
      - ./server/.env
    network_mode: host
    restart: always

  frontend:
    build: ./client
    command: npm run dev -- --host 0.0.0.0 --port 5173
    network_mode: host
    depends_on:
      - backend
    restart: always